apiVersion: apps/v1
kind: Deployment
metadata:
  name: sapient-nginx-deployment
spec:
  selector:
    matchLabels:
      app: sapient-nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: sapient-nginx
    spec:
      containers:
      - name: sapient-nginx-demo
        image: sapient-nginx:latest
        ports:
        - containerPort: 80
